/// Flutter icons HotelBookingConcept
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HotelBookingConcept
///      fonts:
///       - asset: fonts/HotelBookingConcept.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class HotelBookingConcept {
  HotelBookingConcept._();

  static const _kFontFam = 'HotelBookingConcept';

  static const IconData ic_heart_empty = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_search = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_chevron_left = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_location = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_star = const IconData(0xe804, fontFamily: _kFontFam);
}
